# Render deployment configuration
services:
  - type: web
    name: esp-desk
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 3000
